# Generated by Django 4.2 on 2023-05-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sellers_alter_names_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='names',
            options={'verbose_name': 'Наименование', 'verbose_name_plural': 'Наименования'},
        ),
        migrations.AlterField(
            model_name='names',
            name='articul',
            field=models.IntegerField(verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='names',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='bank',
            field=models.CharField(max_length=50, verbose_name='Обслуживающий банк'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='manager',
            field=models.CharField(max_length=50, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='paymentaccount',
            field=models.IntegerField(verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='seller',
            field=models.CharField(max_length=50, verbose_name='Поставщик'),
        ),
    ]
