# Generated by Django 4.2 on 2023-05-11 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_names_options_alter_names_articul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='price',
            field=models.IntegerField(default='100', verbose_name='Цена за 100 грамм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellers',
            name='discount_large',
            field=models.IntegerField(default=0, verbose_name='Наибольший процент скидки при покупке более 1 кг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellers',
            name='discount_small',
            field=models.IntegerField(default=0, verbose_name='Наибольший процент скидки при покупке до 1 кг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='names',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tea', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='names',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sellers', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=100, verbose_name='Промокод')),
                ('time', models.IntegerField(verbose_name='Срок действия(кол-во дней)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tea', verbose_name='Категория')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.names', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
