# Generated by Django 4.2 on 2023-05-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_names_price_sellers_discount_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='time',
            field=models.DateField(verbose_name='Окончание действия промокода'),
        ),
    ]
