# Generated by Django 4.2 on 2023-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_promo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Наличие скидки'),
            preserve_default=False,
        ),
    ]
