# Generated by Django 4.2 on 2023-05-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Категория чая')),
                ('country', models.CharField(max_length=30, verbose_name='Cтрана происхождения')),
            ],
        ),
    ]
