# Generated by Django 4.2 on 2023-05-08 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_tea_options_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=50, verbose_name='Поставщик')),
                ('manager', models.CharField(max_length=50, verbose_name='Менеджер')),
                ('mail', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('payment_account', models.IntegerField(verbose_name='Номер счета')),
                ('bank', models.CharField(max_length=20, verbose_name='Обслуживающий банк')),
            ],
            options={
                'verbose_name': 'Постащик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AlterField(
            model_name='names',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.seller'),
        ),
    ]
