# Generated by Django 4.2 on 2023-05-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_seller_bank_remove_seller_mail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
