# Generated by Django 4.2 on 2023-05-08 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('paymentaccount', models.IntegerField()),
                ('bank', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Постащик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AlterField(
            model_name='names',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.sellers'),
        ),
    ]
